project_name = "rl-project"
entity = "lap1n"
num_episodes= 50
num_workers=10
run_ids=["4cf4oigp","3eivvc17","7spk8k0r","k5qtj4qu","23a0d2s2",
        "3xbp5t2q","1w7lvki7","1y7qeof5","2wxp19j7","1ggrgyws",
        "1g2gbnpv","1zwvl3to","fdm3rdlh","3dg2u633","2qmn6tal",
        "11rppoi5","34zu5vue","1eouuvl1","accx95qv","1f5g1b4f",
        "1u9j7gw2","2fp6zpvy","1k2uhd2e","2pl8q3yt","381yfogm",
        "16ajhp2x","1o2sbjt4","2zbugd5n","91urkn2k","2ywszr0s",
        "2d6m46ji","3m1earoq","1854m7ld","1r09riqt","3w3arvv9",
        "1tw7tgcr","24gkn4do","21jz1m1d","16ldqpyv","2f8hsjeo"]
[filters]
